"""Catalog + model definition → Twenty generated surfaces (pulse-app-scaffold 2.2).

Three outputs from one run, so a catalog state cannot reach one surface and miss another:

- `packages/twenty-app/generated/options.ts` — the SELECT option arrays the hand-written object
  files import. Options are generated, whole object files are not (design Decision 3).
- `packages/twenty-app/generated/projection-lookup.ts` — `<subject>.<state>` → the status field
  and LWW guard the projection handler writes.
- `packages/twenty-app/artifact/operations.json` — the serialized Metadata API operation set:
  objects, fields, relations, picklist options, and the single-writer role set.

Inputs are three checked-in files and nothing else: `catalog/state_catalog.yaml` (through
`catalog_gen.load_catalog`), `pulse_core.twenty_model`'s definition, and
`packages/twenty-app/uid-map.json`. Generation is a pure file transformation — this module opens
no socket and has no path that applies anything to a Twenty instance (design Decision 4: that is
`twenty_deploy`'s job, and it reads this artifact rather than regenerating it).

A `universalIdentifier` the map lacks is a generation error naming the key, never a mint: an
auto-minting generator is nondeterministic by construction and recreates fields on every sync
(design Decision 2).

Regenerate:        uv run python -m pulse_core.twenty_metadata     (task twenty:gen)
Verify (no write): uv run python -m pulse_core.twenty_metadata --check
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pulse_core.catalog_gen import Catalog, load_catalog
from pulse_core.twenty_model import (
    TWENTY_APP_PATH,
    TWENTY_MODEL,
    FieldSpec,
    ModelDefinition,
    ObjectSpec,
    OptionSpec,
    encode_option_value,
    load_uid_map,
    require_uid,
    resolve_options,
    validate_against_catalog,
)

OPTIONS_PATH = TWENTY_APP_PATH / "generated" / "options.ts"
PROJECTION_LOOKUP_PATH = TWENTY_APP_PATH / "generated" / "projection-lookup.ts"
ARTIFACT_PATH = TWENTY_APP_PATH / "artifact" / "operations.json"

#: The artifact contract's own version, independent of the catalog's. It is this repo's contract
#: (design Decision 1), so a shape change is a deliberate bump here plus a deploy-step change —
#: not something a catalog edit can cause.
ARTIFACT_VERSION = "1"

GENERATOR = "pulse_core.twenty_metadata"

_DO_NOT_EDIT = "DO NOT EDIT — generated by `pulse_core.twenty_metadata`. Regenerate: task twenty:gen"

#: The suffix that pairs a status field with its last-writer-wins guard. The pairing is what makes
#: a field a *status* field: one SELECT the projection owns, one DATE_TIME recording when it was
#: last set. Roles and the projection lookup both derive from that pairing rather than from a
#: hand-maintained list, so a new dimension is read-only for staff the moment it is declared.
_AS_OF_SUFFIX = "AsOf"


@dataclass(frozen=True)
class StatusField:
    """One projection-owned dimension on one object: the SELECT and its LWW guard."""

    object_name: str
    status_field: str
    as_of_field: str
    dimension: str | None


@dataclass(frozen=True)
class ProjectionRow:
    """One lookup row: the event type that sets a status field, and the value it sets."""

    event_type: str
    object_name: str
    status_field: str
    as_of_field: str
    value: str


# --- Derivations from the model ---------------------------------------------------------------


def status_fields(model: ModelDefinition) -> tuple[StatusField, ...]:
    """Every SELECT field paired with a `<name>AsOf` guard, sorted by object then field."""
    found: list[StatusField] = []
    for obj in sorted(model.objects, key=lambda o: o.name_singular):
        for field in sorted(obj.fields, key=lambda f: f.name):
            guard = obj.field(f"{field.name}{_AS_OF_SUFFIX}")
            if field.type != "SELECT" or guard is None:
                continue
            found.append(
                StatusField(
                    object_name=obj.name_singular,
                    status_field=field.name,
                    as_of_field=guard.name,
                    dimension=field.dimension,
                )
            )
    return tuple(found)


def projection_rows(model: ModelDefinition, catalog: Catalog) -> tuple[ProjectionRow, ...]:
    """The lookup table: one row per state of every catalog-bound status field, sorted by event type.

    Only dimension-bound status fields produce rows. Provider and Clinic lifecycle are model
    literals at v1 — the catalog carries no provider or clinic dimension, so a row for them would
    assert a grain nobody ratified (task 2.1's HANDOFF note). Those event types stay lookup misses,
    which the handler already treats as no-ops.
    """
    rows = [
        ProjectionRow(
            event_type=f"{entry.dimension}.{state}",
            object_name=entry.object_name,
            status_field=entry.status_field,
            as_of_field=entry.as_of_field,
            value=state,
        )
        for entry in status_fields(model)
        if entry.dimension is not None
        for state in sorted(catalog.subjects[entry.dimension].transitions)
    ]
    return tuple(sorted(rows, key=lambda row: row.event_type))


def _option_uid(uid_map: dict[str, str], obj: ObjectSpec, field: FieldSpec, option: OptionSpec) -> str:
    return require_uid(uid_map, f"{obj.name_singular}.{field.name}.{option.value}")


def _sorted_objects(model: ModelDefinition) -> tuple[ObjectSpec, ...]:
    return tuple(sorted(model.objects, key=lambda obj: obj.name_singular))


def _sorted_fields(obj: ObjectSpec) -> tuple[FieldSpec, ...]:
    return tuple(sorted(obj.fields, key=lambda field: field.name))


# --- generated/options.ts ---------------------------------------------------------------------


def _const_name(obj: ObjectSpec, field: FieldSpec) -> str:
    """`patientProgram`, `lifecycleStatus` -> `PATIENT_PROGRAM_LIFECYCLE_STATUS_OPTIONS`."""
    parts: list[str] = []
    for camel in (obj.name_singular, field.name):
        word = ""
        for character in camel:
            if character.isupper() and word:
                parts.append(word)
                word = ""
            word += character.lower()
        parts.append(word)
    return "_".join(parts).upper() + "_OPTIONS"


# The SDK's `TagColor` union is wider; these ten are the stable cycle options are colored from,
# by position. Presentation only: the artifact carries no color, and a palette edit re-colors
# every board chip without touching an identifier.
_OPTION_COLORS = ("green", "yellow", "orange", "red", "blue", "purple", "gray", "pink", "turquoise", "sky")


def _option_color(position: int) -> str:
    """The palette entry for a 1-based option position, cycling when a picklist outgrows it."""
    return _OPTION_COLORS[(position - 1) % len(_OPTION_COLORS)]


def render_options_ts(model: ModelDefinition, catalog: Catalog, uid_map: dict[str, str]) -> str:
    """The SELECT option arrays, one exported constant per SELECT field plus a keyed index."""
    lines = [
        "/**",
        " * Generated Twenty SELECT options.",
        f" * {_DO_NOT_EDIT}",
        " *",
        " * Options are generated; the object files that import them are hand-written, so a field",
        " * definition stays stable and reviewable while its vocabulary follows the catalog.",
        " *",
        " * The shape is the SDK boundary: `twenty-sdk/define` takes SELECT options as a mutable",
        " * `FieldMetadataComplexOption[]` — `{ id?, value, label, position, color }` — so the arrays",
        " * are typed mutable (never mutated; the object files pass them through by reference, which",
        " * is what `tests/model.test.ts` pins), `id` repeats the minted `universalIdentifier` so the",
        " * server never derives an option identity, and `color` is presentation minted here from a",
        " * fixed palette by position — the artifact deliberately does not carry it.",
        " *",
        " * `encodedValue` is the same option as the live server stores it: v2.30 validates SELECT",
        " * option values as UPPER_CASE snake, so `twenty_deploy` re-encodes every value at the",
        " * deploy boundary (`twenty_validate.encode_option_value`) and the record rows carry the",
        " * encoded form. `value` stays the catalog vocabulary and remains the only thing to reason",
        " * with; `encodedValue` is what any surface keyed on a stored value — a kanban column's",
        " * `fieldValue`, a REST filter — has to use. Demo3's assertion 3 found the board keyed on",
        " * `value`, where no card could ever land.",
        " */",
        "",
        "export type GeneratedOptionColor =",
        "  | " + "\n  | ".join(f'"{color}"' for color in _OPTION_COLORS) + ";",
        "",
        "export interface GeneratedOption {",
        "  readonly value: string;",
        "  readonly encodedValue: string;",
        "  readonly label: string;",
        "  readonly position: number;",
        "  readonly universalIdentifier: string;",
        "  readonly id: string;",
        "  readonly color: GeneratedOptionColor;",
        "}",
        "",
        f'export const CATALOG_VERSION = "{catalog.catalog_version}";',
    ]
    index: list[tuple[str, str]] = []
    for obj in _sorted_objects(model):
        for field in _sorted_fields(obj):
            options = resolve_options(field, catalog)
            if not options:
                continue
            key = f"{obj.name_singular}.{field.name}"
            constant = _const_name(obj, field)
            index.append((key, constant))
            lines.extend(["", f"// {key}", f"export const {constant}: GeneratedOption[] = ["])
            lines.extend(
                f'  {{ value: "{option.value}", encodedValue: "{encode_option_value(option.value)}", '
                f'label: "{option.label}", position: {position}, '
                f'universalIdentifier: "{_option_uid(uid_map, obj, field, option)}", '
                f'id: "{_option_uid(uid_map, obj, field, option)}", color: "{_option_color(position)}" }},'
                for position, option in enumerate(options, start=1)
            )
            lines.append("];")

    lines.extend(["", "export const OPTIONS_BY_FIELD: Readonly<Record<string, GeneratedOption[]>> = {"])
    lines.extend(f'  "{key}": {constant},' for key, constant in index)
    lines.append("};")
    return "\n".join(lines) + "\n"


# --- generated/projection-lookup.ts -----------------------------------------------------------


def render_projection_lookup_ts(model: ModelDefinition, catalog: Catalog) -> str:
    """`<subject>.<state>` → the object, status field, guard field, and value the handler writes."""
    lines = [
        "/**",
        " * Generated projection lookup: event type -> the state it sets.",
        f" * {_DO_NOT_EDIT}",
        " *",
        " * A miss is not an error. Event types with no row here (registry anchors, dimensions the",
        " * model carries as literals) are logged and applied to nothing, which is what the",
        " * unresolved-reference path already does.",
        " */",
        "",
        "export interface ProjectionTarget {",
        "  readonly objectNameSingular: string;",
        "  readonly statusField: string;",
        "  readonly asOfField: string;",
        "  readonly value: string;",
        "}",
        "",
        f'export const CATALOG_VERSION = "{catalog.catalog_version}";',
        "",
        "export const PROJECTION_LOOKUP: Readonly<Record<string, ProjectionTarget>> = {",
    ]
    lines.extend(
        f'  "{row.event_type}": {{ objectNameSingular: "{row.object_name}", statusField: "{row.status_field}", '
        f'asOfField: "{row.as_of_field}", value: "{row.value}" }},'
        for row in projection_rows(model, catalog)
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


# --- artifact/operations.json -----------------------------------------------------------------


def _object_operation(obj: ObjectSpec, uid_map: dict[str, str]) -> dict[str, Any]:
    return {
        "operation": "createObject",
        "universalIdentifier": require_uid(uid_map, obj.name_singular),
        "nameSingular": obj.name_singular,
        "namePlural": obj.name_plural,
        "labelSingular": obj.label_singular,
        "labelPlural": obj.label_plural,
        "icon": obj.icon,
        "description": obj.description,
    }


def _field_operation(obj: ObjectSpec, field: FieldSpec, catalog: Catalog, uid_map: dict[str, str]) -> dict[str, Any]:
    operation: dict[str, Any] = {
        "operation": "createField",
        "universalIdentifier": require_uid(uid_map, f"{obj.name_singular}.{field.name}"),
        "objectNameSingular": obj.name_singular,
        "name": field.name,
        "type": field.type,
        "label": field.label,
        "isNullable": field.is_nullable,
        "isUnique": field.is_unique,
    }
    if field.description is not None:
        operation["description"] = field.description
    if field.default_value is not None:
        operation["defaultValue"] = field.default_value
    options = resolve_options(field, catalog)
    if options:
        operation["options"] = [
            {
                "universalIdentifier": _option_uid(uid_map, obj, field, option),
                "value": option.value,
                "label": option.label,
                "position": position,
            }
            for position, option in enumerate(options, start=1)
        ]
    return operation


def _relation_operation(obj: ObjectSpec, field: FieldSpec, uid_map: dict[str, str]) -> dict[str, Any]:
    """One operation per relation *pair*, emitted from the many side.

    Twenty creates both sides of a relation in one call, and the model declares it twice (task
    2.1's mirroring invariant). Emitting one operation per declaration would ask the deploy step
    to create each relation twice; emitting from the `MANY_TO_ONE` side picks the canonical half
    without losing the other — both identifiers travel in the same operation.
    """
    relation = field.relation
    assert relation is not None  # noqa: S101 — callers filter on `type == "RELATION"`
    target = TWENTY_MODEL.object(relation.target_object)
    assert target is not None  # noqa: S101 — guaranteed by ModelDefinition's relation validator
    inverse = target.field(relation.inverse_field)
    assert inverse is not None  # noqa: S101 — same validator
    return {
        "operation": "createRelation",
        "type": relation.type,
        "from": {
            "universalIdentifier": require_uid(uid_map, f"{obj.name_singular}.{field.name}"),
            "objectNameSingular": obj.name_singular,
            "fieldName": field.name,
            "label": field.label,
            "isNullable": field.is_nullable,
        },
        "to": {
            "universalIdentifier": require_uid(uid_map, f"{target.name_singular}.{inverse.name}"),
            "objectNameSingular": target.name_singular,
            "fieldName": inverse.name,
            "label": inverse.label,
        },
    }


def _object_permission(name: str, *, read: bool, create: bool, update: bool, delete: bool) -> dict[str, Any]:
    return {
        "objectNameSingular": name,
        "canRead": read,
        "canCreate": create,
        "canUpdate": update,
        "canDelete": delete,
    }


def _field_permission(object_name: str, field_name: str, *, update: bool) -> dict[str, Any]:
    return {"objectNameSingular": object_name, "fieldName": field_name, "canRead": True, "canUpdate": update}


def _producer_role() -> dict[str, Any]:
    return {
        "operation": "createRole",
        "name": "producer",
        "label": "Event Producer",
        "description": "The single MCP write path. Creates DomainEvent rows and nothing else.",
        "objectPermissions": [_object_permission("domainEvent", read=False, create=True, update=False, delete=False)],
        "fieldPermissions": [],
    }


def _staff_role(model: ModelDefinition) -> dict[str, Any]:
    """Read/write the entities, read-only on every status field and on DomainEvent.

    Delete stays off everywhere: `twenty-data-model.md` grants staff "read/write entities", and a
    role that can delete a patient is a broader claim than that sentence makes. Widening it later
    is a reviewed diff; narrowing it after an apply is a permission incident.
    """
    entity_objects = sorted(obj.name_singular for obj in model.objects if obj.name_singular != "domainEvent")
    permissions = [
        _object_permission(name, read=True, create=True, update=True, delete=False) for name in entity_objects
    ]
    # Read-only on the log, and read-only on every projection-owned field: the single-writer rule.
    permissions.append(_object_permission("domainEvent", read=True, create=False, update=False, delete=False))
    field_permissions = [
        _field_permission(entry.object_name, field_name, update=False)
        for entry in status_fields(model)
        for field_name in (entry.status_field, entry.as_of_field)
    ]
    return {
        "operation": "createRole",
        "name": "staff",
        "label": "Ops and Clinical Staff",
        "description": "Reads and edits entity records; status fields and the event log are read-only.",
        "objectPermissions": permissions,
        "fieldPermissions": field_permissions,
    }


def _app_role(model: ModelDefinition) -> dict[str, Any]:
    """The projection runtime's role: what `project-domain-event` needs, and nothing more.

    It resolves the entity (read), creates the PatientProgram row on the pair's first event
    (create), writes the status field and its guard (update), and binds the event's relation
    (update on DomainEvent, restricted by field permission to the three relation fields). Create on
    DomainEvent is the optional `log-registration` workflow; delete is off everywhere.
    """
    projection_targets = {entry.object_name for entry in status_fields(model)}
    permissions: list[dict[str, Any]] = []
    for obj in _sorted_objects(model):
        name = obj.name_singular
        if name == "domainEvent":
            permissions.append(_object_permission(name, read=True, create=True, update=True, delete=False))
        else:
            permissions.append(
                _object_permission(
                    name,
                    read=True,
                    create=name in projection_targets,
                    update=name in projection_targets,
                    delete=False,
                )
            )
    domain_event = TWENTY_MODEL.object("domainEvent")
    assert domain_event is not None  # noqa: S101 — the model's own invariant
    field_permissions = [
        _field_permission("domainEvent", field.name, update=False)
        for field in _sorted_fields(domain_event)
        if field.type != "RELATION"
    ]
    return {
        "operation": "createRole",
        "name": "app",
        "label": "Projection App",
        "description": "The projection runtime: resolves entities, applies status per the lookup, binds relations.",
        "objectPermissions": permissions,
        "fieldPermissions": field_permissions,
    }


def build_operations(model: ModelDefinition, catalog: Catalog, uid_map: dict[str, str]) -> dict[str, Any]:
    """The whole operation set, in the provisioning order twenty-data-model.md's setup section names.

    Objects → fields → relations → roles. Picklist options ride inside their field operation rather
    than as a fourth phase: an option without its field is not applicable, and keeping them together
    means one operation carries one reviewable unit of the model.
    """
    objects = [_object_operation(obj, uid_map) for obj in _sorted_objects(model)]
    fields = [
        _field_operation(obj, field, catalog, uid_map)
        for obj in _sorted_objects(model)
        for field in _sorted_fields(obj)
        if field.type != "RELATION"
    ]
    relations = [
        _relation_operation(obj, field, uid_map)
        for obj in _sorted_objects(model)
        for field in _sorted_fields(obj)
        if field.relation is not None and field.relation.type == "MANY_TO_ONE"
    ]
    roles = [_producer_role(), _staff_role(model), _app_role(model)]
    return {
        "artifactVersion": ARTIFACT_VERSION,
        "catalogVersion": catalog.catalog_version,
        "generator": GENERATOR,
        "operations": [*objects, *fields, *relations, *roles],
    }


def render_artifact(model: ModelDefinition, catalog: Catalog, uid_map: dict[str, str]) -> str:
    return json.dumps(build_operations(model, catalog, uid_map), indent=2) + "\n"


# --- Generation ------------------------------------------------------------------------------


def generate(model: ModelDefinition, catalog: Catalog, uid_map: dict[str, str]) -> dict[Path, str]:
    """Render every surface in memory, keyed by the path it belongs at. Writes nothing."""
    validate_against_catalog(model, catalog)
    return {
        OPTIONS_PATH: render_options_ts(model, catalog, uid_map),
        PROJECTION_LOOKUP_PATH: render_projection_lookup_ts(model, catalog),
        ARTIFACT_PATH: render_artifact(model, catalog, uid_map),
    }


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: write the generated surfaces, or verify the committed ones with --check."""
    parser = argparse.ArgumentParser(description="Generate the Twenty app's surfaces and metadata artifact.")
    parser.add_argument("--check", action="store_true", help="verify the committed surfaces are current")
    args = parser.parse_args(argv)

    rendered = generate(TWENTY_MODEL, load_catalog(), load_uid_map())
    if args.check:
        stale = sorted(path for path, text in rendered.items() if not path.exists() or path.read_text() != text)
        for path in stale:
            print(f"{path} is stale — run: task twenty:gen")
        return 1 if stale else 0
    for path, text in sorted(rendered.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
