"""Unit tests for control-plane ticket handlers."""

from __future__ import annotations

import os
import sys
import uuid
from unittest.mock import AsyncMock, MagicMock

# Allow importing src package from service root
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_ticket_created_event(
    category: str = "device_issue",
    priority: str = "high",
    patient_id: str = "patient-001",
    description: str = "Device not syncing",
    task_ids: list[str] | None = None,
    alert_ids: list[str] | None = None,
) -> dict:
    payload = {
        "category": category,
        "priority": priority,
        "patient_id": patient_id,
        "description": description,
    }
    if task_ids is not None:
        payload["task_ids"] = task_ids
    if alert_ids is not None:
        payload["alert_ids"] = alert_ids
    return {
        "event_id": str(uuid.uuid4()),
        "event_type": "ticket.created",
        "timestamp": "2026-03-11T10:00:00Z",
        "source_system": "slack-bot",
        "entity_id": "",  # ticket_id generated by handler
        "entity_type": "ticket",
        "correlation_id": "corr-ticket-001",
        "payload": payload,
    }


def _make_ticket_updated_event(
    ticket_id: str = "ticket-abc",
    new_status: str = "in_progress",
    priority: str | None = None,
    waiting_reason: str | None = None,
    task_ids: list[str] | None = None,
    alert_ids: list[str] | None = None,
) -> dict:
    payload: dict = {"new_status": new_status}
    if priority is not None:
        payload["priority"] = priority
    if waiting_reason is not None:
        payload["waiting_reason"] = waiting_reason
    if task_ids is not None:
        payload["task_ids"] = task_ids
    if alert_ids is not None:
        payload["alert_ids"] = alert_ids
    return {
        "event_id": str(uuid.uuid4()),
        "event_type": "ticket.updated",
        "timestamp": "2026-03-11T11:00:00Z",
        "source_system": "control-plane",
        "entity_id": ticket_id,
        "entity_type": "ticket",
        "correlation_id": "corr-ticket-002",
        "payload": payload,
    }


def _mock_sequence_result(seq_val: int = 1):
    """Create a mock result for SELECT nextval() returning seq_val."""
    result = MagicMock()
    result.scalar_one.return_value = seq_val
    return result


# ---------------------------------------------------------------------------
# handle_ticket_created tests
# ---------------------------------------------------------------------------


class TestHandleTicketCreated:
    @pytest.mark.asyncio
    async def test_writes_ticket_and_publishes_event(self):
        """handle_ticket_created inserts ticket row and publishes ticket.created to ocean.tickets."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(1))
        producer = AsyncMock()
        event = _make_ticket_created_event()

        await handle_ticket_created(event, session, producer=producer)

        # At least 1 DB call (INSERT ticket) + 1 sequence call
        assert session.execute.call_count >= 2
        assert producer.publish.called
        topic, pub_event = producer.publish.call_args[0]
        assert topic == "ocean.tickets"
        assert pub_event["event_type"] == "ticket.created"

    @pytest.mark.asyncio
    async def test_generates_correct_human_id_format(self):
        """human_id follows {PREFIX}-{seq:05d} pattern."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(42))
        producer = AsyncMock()
        event = _make_ticket_created_event(category="device_issue")

        await handle_ticket_created(event, session, producer=producer)

        pub_event = producer.publish.call_args[0][1]
        assert pub_event["payload"]["human_id"] == "DEV-00042"

    @pytest.mark.asyncio
    async def test_clinical_support_human_id(self):
        """clinical_support category generates CLN prefix."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(7))
        producer = AsyncMock()
        event = _make_ticket_created_event(category="clinical_support")

        await handle_ticket_created(event, session, producer=producer)

        pub_event = producer.publish.call_args[0][1]
        assert pub_event["payload"]["human_id"] == "CLN-00007"

    @pytest.mark.asyncio
    async def test_links_tasks_via_bridge_table(self):
        """When task_ids provided, INSERT INTO ticket_tasks for each."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(1))
        producer = AsyncMock()
        event = _make_ticket_created_event(task_ids=["task-1", "task-2"])

        await handle_ticket_created(event, session, producer=producer)

        # 1 seq + 1 ticket INSERT + 2 ticket_tasks INSERTs = 4
        assert session.execute.call_count >= 4
        # Check that task_id params were passed for bridge inserts
        all_params = [c[0][1] for c in session.execute.call_args_list if len(c[0]) > 1]
        task_id_params = [p.get("task_id") for p in all_params if "task_id" in p]
        assert "task-1" in task_id_params
        assert "task-2" in task_id_params

    @pytest.mark.asyncio
    async def test_links_alerts_via_bridge_table(self):
        """When alert_ids provided, INSERT INTO ticket_alerts for each."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(1))
        producer = AsyncMock()
        event = _make_ticket_created_event(alert_ids=["alert-1"])

        await handle_ticket_created(event, session, producer=producer)

        all_params = [c[0][1] for c in session.execute.call_args_list if len(c[0]) > 1]
        alert_id_params = [p.get("alert_id") for p in all_params if "alert_id" in p]
        assert "alert-1" in alert_id_params

    @pytest.mark.asyncio
    async def test_no_producer_does_not_raise(self):
        """Without a producer, handler completes without error."""
        from src.handlers.tickets import handle_ticket_created

        session = AsyncMock()
        session.execute = AsyncMock(return_value=_mock_sequence_result(1))
        event = _make_ticket_created_event()

        await handle_ticket_created(event, session, producer=None)
        assert session.execute.called


# ---------------------------------------------------------------------------
# handle_ticket_updated tests
# ---------------------------------------------------------------------------


class TestHandleTicketUpdated:
    @pytest.mark.asyncio
    async def test_valid_transition_updates_and_publishes(self):
        """Legal transition (open->in_progress) updates DB and publishes ticket.updated."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        # Mock the SELECT to return current status
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = "open"
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="in_progress")

        await handle_ticket_updated(event, session, producer=producer)

        assert producer.publish.called
        pub_event = producer.publish.call_args[0][1]
        assert pub_event["event_type"] == "ticket.updated"

    @pytest.mark.asyncio
    async def test_illegal_transition_skips(self):
        """Illegal transition (resolved->open) does not publish."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = "resolved"
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="open")

        await handle_ticket_updated(event, session, producer=producer)

        producer.publish.assert_not_called()

    @pytest.mark.asyncio
    async def test_resolved_publishes_ticket_resolved(self):
        """Transition to 'resolved' publishes ticket.updated, ticket.resolved and outcome.recorded."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = "in_progress"
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="resolved")

        await handle_ticket_updated(event, session, producer=producer)

        # Resolution dual-publishes: the ticket pair, plus outcome.recorded to ocean.outcomes
        # (phase 22 wired every resolution path through build_outcome_event).
        assert producer.publish.call_count == 3
        event_types = [c[0][1]["event_type"] for c in producer.publish.call_args_list]
        assert "ticket.updated" in event_types
        assert "ticket.resolved" in event_types
        assert "outcome.recorded" in event_types
        outcome_topic = next(
            c[0][0] for c in producer.publish.call_args_list if c[0][1]["event_type"] == "outcome.recorded"
        )
        assert outcome_topic == "ocean.outcomes"

    @pytest.mark.asyncio
    async def test_priority_change_updates(self):
        """Priority change in payload is included in the UPDATE."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = "open"
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="in_progress", priority="critical")

        await handle_ticket_updated(event, session, producer=producer)

        # Verify the UPDATE was called with priority param
        all_params = [c[0][1] for c in session.execute.call_args_list if len(c[0]) > 1]
        priority_params = [p.get("priority") for p in all_params if "priority" in p]
        assert "critical" in priority_params

    @pytest.mark.asyncio
    async def test_ticket_not_found_skips(self):
        """If ticket doesn't exist (status is None), handler skips."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = None
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="in_progress")

        await handle_ticket_updated(event, session, producer=producer)

        producer.publish.assert_not_called()

    @pytest.mark.asyncio
    async def test_bridge_links_on_update(self):
        """New task_ids in update payload are linked via bridge table."""
        from src.handlers.tickets import handle_ticket_updated

        session = AsyncMock()
        status_result = MagicMock()
        status_result.scalar_one_or_none.return_value = "open"
        session.execute = AsyncMock(return_value=status_result)
        producer = AsyncMock()
        event = _make_ticket_updated_event(new_status="in_progress", task_ids=["task-new"])

        await handle_ticket_updated(event, session, producer=producer)

        # Verify bridge insert was called with the task_id param
        all_params = [c[0][1] for c in session.execute.call_args_list if len(c[0]) > 1]
        task_id_params = [p.get("task_id") for p in all_params if "task_id" in p]
        assert "task-new" in task_id_params
