"""Gate 1: Structure & Layout Contract.

Every path the README's target tree promises exists, and each is in the delivery class the
scaffold actually supports.

Usage: uv run pytest tests/scaffold/cat1_structure.py -v

The delivery classes matter because `gh repo create --template` clones only *committed* content.
Anything gitignored or empty does not reach a generated repo, so bootstrap.sh must recreate it.
Both bootstrap failures on 2026-07-31 were this class: `.openlore/` is gitignored (so `openlore
analyze` had no config) and `openspec/specs/` was empty (so the openlore-drift hook hard-failed).
"""

import re
from pathlib import Path

import pytest

from ._scaffold import ROOT, git, template_only, tomllib

# --- Delivery classes, derived from the README target tree -------------------------------------

# Committed: present on disk AND tracked by git, so a template clone receives them.
COMMITTED = [
    ".github/workflows",
    ".claude/commands/opsx",
    ".claude/settings.json",
    ".env.example",
    ".mcp.json",
    ".python-version",
    "docs/adr/ADR-0000-template.md",
    "docs/ci-lessons.md",
    "docs/contracts/publishes.md",
    "docs/contracts/consumes.md",
    "openspec/specs/.gitkeep",
    "openspec/changes/archive/.gitkeep",
    "scripts/template_sync.sh",
    "src/pkg_pulse/py.typed",
    ".pre-commit-config.yaml",
    "AGENTS.md",
    "CLAUDE.md",
    "README.md",
    "WORKFLOW.md",
    "Taskfile.yml",
    "docs",
    "openspec/config.yaml",
    "pyproject.toml",
    "scripts/dispatch_tasks.py",
    "scripts/collect_handoffs.py",
    "scripts/workflow.py",
    "scripts/linear_sync.py",
    "src/pkg_pulse",
    "templates/HANDOFF.md",
    "tests",
    "tests/scaffold",
    "uv.lock",
]

# Generated by tooling and gitignored. Absent from a fresh template clone by design;
# bootstrap.sh runs `openlore init && openlore analyze` to create them.
#
# Directory entries keep their trailing slash: a `work_orders/` pattern in .gitignore only
# matches a query git can tell is a directory, and these paths often do not exist yet.
GENERATED = [".openlore/", ".openlore/analysis/"]

# Per-session working state. Gitignored, may not exist at all.
PER_SESSION = ["work_orders/", "handoffs/", "HANDOFF.md"]

# Written by bootstrap.sh into the generated repo and committed there, but deliberately absent
# from the template itself: repo-ade is not generated from anything, so a version stamp here
# would name a commit of itself and `task template:diff` would compare the repo to its own past.
DOWNSTREAM_ONLY = [".ade-template-version"]

# Committed-but-empty directories. Git cannot track an empty directory, so these never arrive
# via a template expansion even though the target tree shows them — bootstrap.sh recreates them
# with `mkdir -p`. Removing that mkdir must fail this gate.
EMPTY_SCAFFOLD_DIRS = ["openspec/specs", "openspec/changes"]

# Names in the target tree that are illustrative, not real paths.
TREE_PLACEHOLDERS = {"your-project", "<change-name>", "<capability>", "<package_name>"}

# Files that exist only inside a placeholder subtree (openspec/changes/<change-name>/...).
TREE_EXAMPLE_ONLY = {"proposal.md", "design.md", "tasks.md", "spec.md"}


def _tree_entries() -> set[str]:
    """Basenames from the README target-tree fence, minus glyphs, comments and placeholders."""
    readme = (ROOT / "README.md").read_text()
    block = re.search(r"```\n(your-project/.*?)```", readme, re.DOTALL)
    assert block, "README.md must contain a fenced target-tree diagram starting with your-project/"
    names = set()
    for line in block.group(1).splitlines():
        stripped = re.sub(r"^[\s│├└─]+", "", line).split("#")[0].strip()
        if stripped:
            names.add(stripped.rstrip("/"))
    return names - TREE_PLACEHOLDERS - TREE_EXAMPLE_ONLY


@pytest.mark.parametrize("rel", COMMITTED)
def test_committed_path_exists(rel: str) -> None:
    assert (ROOT / rel).exists(), f"README target tree promises {rel}"


@pytest.mark.parametrize("rel", COMMITTED)
def test_committed_path_is_tracked(rel: str) -> None:
    """Untracked means a template clone will not receive it, however present it is locally."""
    assert git("ls-files", "--", rel).stdout.strip(), f"{rel} exists but git does not track it"


# EMPTY_SCAFFOLD_DIRS now ship tracked .gitkeep markers (see COMMITTED), so they do arrive in a
# fresh clone and their existence is covered by test_committed_path_exists. bootstrap.sh still
# recreates them because it deletes openspec/changes/ wholesale, taking that marker with it —
# both mechanisms are load-bearing, for different reasons.
#
# An earlier version asserted these directories exist *without* the markers, which held only in
# a bootstrapped working copy and failed every generated repo's first `task test`. Gate 9's
# fresh-clone smoke is what caught it.


@pytest.mark.parametrize("rel", EMPTY_SCAFFOLD_DIRS)
def test_bootstrap_recreates_empty_scaffold_dirs(rel: str) -> None:
    """Git cannot carry an empty dir, so bootstrap.sh is the only thing that can restore it."""
    bootstrap = (ROOT / "bootstrap.sh").read_text()
    assert re.search(rf"mkdir -p[^\n]*{re.escape(rel)}", bootstrap), (
        f"bootstrap.sh must `mkdir -p {rel}` — a template clone never receives an empty directory"
    )


@pytest.mark.parametrize("rel", PER_SESSION + GENERATED)
def test_working_state_is_gitignored(rel: str) -> None:
    assert git("check-ignore", rel).returncode == 0, f"{rel} must be gitignored"


def test_template_handoff_is_not_ignored() -> None:
    """`/HANDOFF.md` is root-anchored so the tracked template survives. Unanchor it and this fails."""
    assert git("check-ignore", "templates/HANDOFF.md").returncode != 0, (
        "templates/HANDOFF.md must stay tracked; check that .gitignore anchors /HANDOFF.md"
    )


def test_package_layout_matches_manifest() -> None:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text())
    packages = data["tool"]["hatch"]["build"]["targets"]["wheel"]["packages"]
    for pkg in packages:
        assert (ROOT / pkg / "__init__.py").is_file(), f"{pkg}/__init__.py missing"


def test_package_ships_a_pep561_marker() -> None:
    """Without py.typed a consumer's strict type checker treats the package as untyped."""
    data = tomllib.loads((ROOT / "pyproject.toml").read_text())
    for pkg in data["tool"]["hatch"]["build"]["targets"]["wheel"]["packages"]:
        assert (ROOT / pkg / "py.typed").is_file(), f"{pkg}/py.typed missing (PEP 561)"


def test_env_example_holds_no_values() -> None:
    """`.env.example` is committed; a filled-in value here is a leaked secret."""
    for line in (ROOT / ".env.example").read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        assert not value.strip(), f".env.example must ship empty keys; {key} has a value"


def test_single_source_package() -> None:
    """bootstrap.sh derives the old package name from `ls src/`, which needs exactly one entry."""
    entries = [p for p in (ROOT / "src").iterdir() if p.is_dir() and not p.name.startswith("__")]
    assert len(entries) == 1, f"bootstrap.sh assumes one package under src/, found {entries}"


def test_shell_scripts_are_executable_in_the_index() -> None:
    """A mode difference between template and generated repo shows up as patch noise.

    bootstrap.sh was committed 100644 here but chmod +x'd during generation, so every generated
    repo carried 100755 and `task template:sync` warned "has type 100755, expected 100644" on
    every run.
    """
    listing = git("ls-files", "-s", "*.sh").stdout.splitlines()
    assert listing, "no shell scripts tracked"
    not_executable = [line.split("\t")[-1] for line in listing if not line.startswith("100755")]
    assert not not_executable, (
        f"tracked shell scripts must be mode 100755: {not_executable} — fix with `git update-index --chmod=+x <path>`"
    )


def test_no_orphan_task_runner() -> None:
    """The docs designate go-task; a leftover Makefile/justfile means two competing runners."""
    for orphan in ("Makefile", "justfile", "Justfile"):
        assert not (ROOT / orphan).exists(), f"{orphan} competes with Taskfile.yml"


@template_only
def test_every_tree_entry_is_classified() -> None:
    """A new target-tree entry that nobody classified is a gap in this gate, not a pass.

    The tree renders entries at varying depth ('.claude', 'commands/opsx', '.github/workflows'),
    so a classified path is matched against every contiguous slice of its components.
    """
    known: set[str] = set()
    for group in (COMMITTED, GENERATED, PER_SESSION, EMPTY_SCAFFOLD_DIRS, DOWNSTREAM_ONLY):
        for rel in group:
            parts = Path(rel.rstrip("/")).parts
            for i in range(len(parts)):
                for j in range(i + 1, len(parts) + 1):
                    known.add("/".join(parts[i:j]))
    unclassified = {e for e in _tree_entries() if e not in known}
    assert not unclassified, (
        f"README target tree lists {sorted(unclassified)} but cat1 does not classify them as "
        "COMMITTED / GENERATED / PER_SESSION / EMPTY_SCAFFOLD_DIRS / DOWNSTREAM_ONLY"
    )


@pytest.mark.parametrize("rel", DOWNSTREAM_ONLY)
@template_only
def test_downstream_only_paths_absent_from_the_template(rel: str) -> None:
    """A template that carries a generated repo's state ships that state to every clone.

    Only meaningful in the template. The first version asserted unconditionally and so failed
    every generated repo's first `task test` — the file it forbids is one bootstrap.sh
    deliberately writes. Gate 9 could not catch that, because it clones the template, where the
    assertion holds; only a real generated repo exposes it.

    The remote is the discriminator. Checking for the file itself would be circular: the test
    would skip in exactly the case it exists to catch.
    """
    assert not (ROOT / rel).exists(), f"{rel} belongs in a generated repo, not in the template — bootstrap.sh writes it"
