#!/usr/bin/env bash
# Gate 7: Gates & Hooks Enforcement
#
# The quality gates actually fire and actually block. Everything destructive happens in a
# throwaway sandbox built with `git archive HEAD`, so the real repo, its .git directory and its
# working tree are never touched.
#
# The sandbox setup doubles as a check on the bootstrap contract: `git archive` carries only
# committed content, so the sandbox needs exactly what bootstrap.sh recreates — `openlore init`
# for the gitignored .openlore/ config, and `mkdir -p openspec/specs` for the empty directory git
# cannot track. Drop either and the drift hook hard-fails.
#
# Usage: ./tests/scaffold/cat7_gates_hooks.sh
set -uo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)

PASS=0
FAIL=0

pass() { echo "PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $1"; FAIL=$((FAIL + 1)); }

check() {
  local label=$1
  shift
  if "$@" >/dev/null 2>&1; then pass "$label"; else fail "$label"; fi
}

refute() {
  local label=$1
  shift
  if "$@" >/dev/null 2>&1; then fail "$label (unexpectedly succeeded)"; else pass "$label"; fi
}

echo "Gate 7: Gates & Hooks Enforcement"
echo ""

# --- hook ownership on the real repo (read-only) ---
HOOK="$ROOT/.git/hooks/pre-commit"
if [ -f "$HOOK" ]; then
  if grep -q "generated by pre-commit" "$HOOK"; then
    pass "the pre-commit framework owns .git/hooks/pre-commit"
  else
    fail "a raw script owns .git/hooks/pre-commit — it is fighting the framework shim"
  fi
  refute "no openlore-written hook competing with the framework" grep -q "openlore drift" "$HOOK"
else
  fail ".git/hooks/pre-commit is not installed — run 'uv run pre-commit install'"
fi

# --- hook inventory is wired in config ---
for id in check-case-conflict check-merge-conflict check-toml check-yaml check-json \
  pretty-format-json end-of-file-fixer trailing-whitespace ruff-check ruff-format openlore-drift; do
  check "hook configured: $id" grep -q "id: ${id}\$" "$ROOT/.pre-commit-config.yaml"
done

# --- drift is clean on the real committed tree ---
if command -v openlore >/dev/null 2>&1; then
  check "openlore drift clean on the real repo" bash -c "cd '$ROOT' && openlore drift --fail-on warning"
else
  echo "SKIP: openlore not installed"
fi

# --- sandbox: prove the hooks install and block ---
PRECOMMIT="$ROOT/.venv/bin/pre-commit"
if [ ! -x "$PRECOMMIT" ]; then
  fail "$PRECOMMIT missing — run 'task install' before gate 7"
  echo ""
  echo "Gate 7: $PASS passed, $FAIL failed"
  exit 1
fi

SANDBOX=$(mktemp -d)
trap 'rm -rf "$SANDBOX"' EXIT

git -C "$ROOT" archive HEAD | tar -x -C "$SANDBOX"
(
  cd "$SANDBOX" || exit 1
  git init -q
  git config user.email scaffold@test.invalid
  git config user.name "Scaffold Gate"
  # What bootstrap.sh recreates, because git cannot deliver it.
  openlore init >/dev/null 2>&1
  mkdir -p openspec/specs openspec/changes/archive
) || { fail "sandbox setup failed"; echo ""; echo "Gate 7: $PASS passed, $FAIL failed"; exit 1; }

check "hooks install into the sandbox" bash -c "cd '$SANDBOX' && '$PRECOMMIT' install"
check "sandbox hook is the framework shim" grep -q "generated by pre-commit" "$SANDBOX/.git/hooks/pre-commit"

# A commit of the committed tree must pass every hook.
if (cd "$SANDBOX" && git add -A && git commit -qm "sandbox baseline") >/dev/null 2>&1; then
  pass "clean commit passes all hooks"
else
  fail "clean commit was blocked — run '$PRECOMMIT run --all-files' in the sandbox to see why"
fi

# Every hook id must actually have run, not merely be configured.
HOOK_OUTPUT=$(cd "$SANDBOX" && "$PRECOMMIT" run --all-files 2>&1)
for id in ruff-check ruff-format openlore-drift; do
  if echo "$HOOK_OUTPUT" | grep -qi "$(echo "$id" | tr '-' ' ')\|$id"; then
    pass "hook ran on commit: $id"
  else
    fail "hook did not run: $id"
  fi
done

# A lint violation must block the commit. The package directory is derived rather than hardcoded:
# bootstrap.sh renames it per project, and its find-and-replace does not cover *.sh files.
PKG=$(basename "$(find "$SANDBOX/src" -mindepth 1 -maxdepth 1 -type d | head -1)")
if [ -z "$PKG" ]; then
  fail "no package directory under src/ in the sandbox"
else
  printf 'import os\nx=  1\n' > "$SANDBOX/src/$PKG/bad.py"
  (cd "$SANDBOX" && git add "src/$PKG/bad.py") >/dev/null 2>&1
  refute "lint violation blocks the commit" bash -c "cd '$SANDBOX' && git commit -qm bad"
  rm -f "$SANDBOX/src/$PKG/bad.py"
fi

# Drift must be clean in a freshly bootstrapped sandbox.
check "drift clean in the bootstrapped sandbox" bash -c "cd '$SANDBOX' && openlore drift --fail-on warning"

echo ""
echo "Gate 7: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
